#! /bin/bash

export DOT_DIR=$(pwd)
echo $DOT_DIR

function install()
{
	./$1/install
}

if [ $# -ne 1 ]; then
	echo "usage: $0 [package]"
	exit 1
fi

if [ -d $1 ]; then
	echo "Installing $1"
	install $1
	if [ $? -eq 0 ]; then
		echo "finished install of $1"
	else
		echo "failed install of $1"
		exit 1
	fi
else
	echo "cannot find install package for $1"
fi
