#! /bin/bash
# Requires: git

if [ -e ~/.powerline ]; then
	echo "Powerline dir at ~/.powerline already exists, remove to reinstall"
else
	git clone git://github.com/Lokaltog/powerline ~/.powerline
fi

if [ -e ~/.powerline-fonts ]; then
	echo "Powerline fonts already downloaded"
else
	git clone git://github.com/Lokaltog/powerline-fonts ~/.powerline-fonts
fi

# Add fonts
mkdir -p ~/.config/fontconfig/conf.d/
mkdir -p ~/.fonts
cp ~/.powerline/font/10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
cp ~/.powerline/font/PowerlineSymbols.otf ~/.fonts
cp ~/.powerline-fonts/Inconsolata/Inconsolata\ for\ Powerline.otf ~/.fonts
fc-cache -vf ~/.fonts

cp ${DOT_DIR}/tmux/tmux.conf ~/.tmux.conf
echo 'export PATH=$PATH:$HOME/.powerline/scripts' >> ~/.bashrc
echo 'export PATH=$PATH:$HOME/.powerline/scripts' >> ~/.zshrc

mkdir -p ~/.config/powerline
cp -r ~/.powerline/powerline/config_files/* ~/.config/powerline

cp ${DOT_DIR}/tmux/powerline.json ~/.config/powerline/themes/tmux/default.json

echo "source-file '$HOME/.powerline/powerline/bindings/tmux/powerline.conf'" >> ~/.tmux.conf
