#! /bin/bash
# Requires: git, zsh, wget, sed

# Install Oh My ZSH
if [ -d ~/.oh-my-zsh ]; then
	echo "Oh-my-zsh already installed, remove .oh-my-zsh and retry to reinstall"
else
	echo "Installing oh-my-zsh"
	wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh
fi

# Set the zsh theme to dstufft
sed -i -e 's/^plugins=.*/plugins=(git mvn debian screen)/' -e 's/^ZSH_THEME=.*/ZSH_THEME=darkblood/' ~/.zshrc

echo "" >> ~/.zshrc
echo "source ~/.bash_aliases" >> ~/.zshrc
echo "source ${DOT_DIR}/till.sh" >> ~/.zshrc

# Change default shell to zsh
USER=$( whoami )
echo "chsh... "
# sudo chsh -s $(which zsh) $USER
