#! /bin/bash
# Requires: git, zsh, wget, sed

# Install Oh My ZSH
if [ -d ~/.oh-my-zsh ]; then
	echo "Oh-my-zsh already installed, remove .oh-my-zsh and retry to reinstall"
else
	echo "Installing oh-my-zsh"
	wget --no-check-certificate http://install.ohmyz.sh -O - | sh
	if [ "$!" != "0" ]; then
		echo "Failed to download with wget"
		git clone git://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
        cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
	fi
fi

echo "Adding setting OH_MY_ZSH plugin configuration"
# Set the zsh theme to dstufft
sed -i -e 's/^plugins=.*/plugins=(git mvn tmux screen)/' ~/.zshrc
sed -i -e 's/^ZSH_THEME=.*/ZSH_THEME=darkblood/' ~/.zshrc

echo "" >> ~/.zshrc
echo "source ~/.bash_aliases" >> ~/.zshrc
echo "source ${DOT_DIR}/till.sh" >> ~/.zshrc

# Change default shell to zsh
USER=$( whoami )
echo "chsh... "
# sudo chsh -s $(which zsh) $USER
